
package org.tongji;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "ReportServiceSoap", targetNamespace = "http://tongji.org")
public interface ReportServiceSoap {

	/**
	 * 
	 * @param pInput
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "XMLService", action = "http://tongji.org/Tongji.Soap.Service.NSDPService.XMLService")
	@WebResult(name = "XMLServiceResult", targetNamespace = "http://tongji.org")
	@RequestWrapper(localName = "XMLService", targetNamespace = "http://tongji.org", className = "org.tongji.XMLService")
	@ResponseWrapper(localName = "XMLServiceResponse", targetNamespace = "http://tongji.org", className = "org.tongji.XMLServiceResponse")
	public String xmlService(@WebParam(name = "pInput", targetNamespace = "http://tongji.org") String pInput);

}
