
package com.th.supcom.eif.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "WebServiceInterfaceService", targetNamespace = "http://webService.eif.supcom.th.com/", wsdlLocation = "http://192.18.100.92:8080/eif-server/webService/eifWebService?wsdl")
public class WebServiceInterfaceService
    extends Service
{

    private final static URL WEBSERVICEINTERFACESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.th.supcom.eif.webservice.WebServiceInterfaceService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.th.supcom.eif.webservice.WebServiceInterfaceService.class.getResource(".");
            url = new URL(baseUrl, "http://192.18.100.92:8080/eif-server/webService/eifWebService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://192.18.100.92:8080/eif-server/webService/eifWebService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        WEBSERVICEINTERFACESERVICE_WSDL_LOCATION = url;
    }

    public WebServiceInterfaceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebServiceInterfaceService() {
        super(WEBSERVICEINTERFACESERVICE_WSDL_LOCATION, new QName("http://webService.eif.supcom.th.com/", "WebServiceInterfaceService"));
    }

    /**
     * 
     * @return
     *     returns WebServiceInterface
     */
    @WebEndpoint(name = "WebServiceInterfacePort")
    public WebServiceInterface getWebServiceInterfacePort() {
        return super.getPort(new QName("http://webService.eif.supcom.th.com/", "WebServiceInterfacePort"), WebServiceInterface.class);
    }

}
