
package com.th.supcom.eif.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "WebServiceInterface", targetNamespace = "http://webService.eif.supcom.th.com/")
public interface WebServiceInterface {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "acceptOutMessageReturn", targetNamespace = "")
    @RequestWrapper(localName = "acceptOutMessage", targetNamespace = "http://webService.eif.supcom.th.com/", className = "com.th.supcom.eif.webservice.AcceptOutMessage")
    @ResponseWrapper(localName = "acceptOutMessageResponse", targetNamespace = "http://webService.eif.supcom.th.com/", className = "com.th.supcom.eif.webservice.AcceptOutMessageResponse")
    public String acceptOutMessage(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "acceptMessageReturn", targetNamespace = "")
    @RequestWrapper(localName = "acceptMessage", targetNamespace = "http://webService.eif.supcom.th.com/", className = "com.th.supcom.eif.webservice.AcceptMessage")
    @ResponseWrapper(localName = "acceptMessageResponse", targetNamespace = "http://webService.eif.supcom.th.com/", className = "com.th.supcom.eif.webservice.AcceptMessageResponse")
    public String acceptMessage(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "acceptAppointMessageReturn", targetNamespace = "")
    @RequestWrapper(localName = "acceptAppointMessage", targetNamespace = "http://webService.eif.supcom.th.com/", className = "com.th.supcom.eif.webservice.AcceptAppointMessage")
    @ResponseWrapper(localName = "acceptAppointMessageResponse", targetNamespace = "http://webService.eif.supcom.th.com/", className = "com.th.supcom.eif.webservice.AcceptAppointMessageResponse")
    public String acceptAppointMessage(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "acceptRowaMessageReturn", targetNamespace = "")
    @RequestWrapper(localName = "acceptRowaMessage", targetNamespace = "http://webService.eif.supcom.th.com/", className = "com.th.supcom.eif.webservice.AcceptRowaMessage")
    @ResponseWrapper(localName = "acceptRowaMessageResponse", targetNamespace = "http://webService.eif.supcom.th.com/", className = "com.th.supcom.eif.webservice.AcceptRowaMessageResponse")
    public String acceptRowaMessage(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws Exception_Exception
    ;

}
